openapi: 3.0.1
info:
  title: mockyapi
  description: API Definition of mockyapi
  version: 1.0.0
servers:
- url: http://localhost:8290/mockyapi
paths:
  /fetch:
    get:
      responses:
        default:
          description: Default response
